### ISSUE TITLE
Tracking issue for openssl 0.11

### ISSUE THREAD

**Issue by alex** [sfackler/rust-openssl#2298]
This will be the next semver-incompatible upgrade. (Note that this will only be the openssl crate, not openssl-sys):

- [ ] Upgrade `foreign-types`: https://github.com/sfackler/rust-openssl/issues/2297
- [ ] Drop support for OpenSSL<1.1
- [ ] Drop support for older LibreSSL
- [ ] ...
